---
name: Tests

on:
  workflow_call:

jobs:
  # https://github.com/rhysd/actionlint
  action_lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Action Lint
        uses: rhysd/actionlint@v1.7.12

  # https://github.com/arthurnn/code-scanning-rubocop
  rubocop:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          # runs 'bundle install' and caches installed gems automatically
          # ruby-version: 4.0.5 - uses .ruby-version file

      - name: Rubocop
        run: bundle exec rubocop --display-cop-names

  theme-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'

      - name: Install theme-check
        run: gem install theme-check

      - name: Run theme-check
        run: theme-check .

  yaml_lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Yaml Lint
        uses: bewuethr/yamllint-action@v1
        with:
          config-file: .yamllint
